// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lafguwdkqlrzojgmaeul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZmd1d2RrcWxyem9qZ21hZXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTgwOTEsImV4cCI6MjA3MjA3NDA5MX0.YHI_dmVDBkx6TwRS7d3_4rt1UKZCuo_7QptUBFNINrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});